model:
  # ckpt: "results/MultiTask/audio_free/stage1_model"
  # stage2 model
  # ckpt: "results/MultiTask/audio_free/stage2_model"
  # ckpt: "results/MultiTask/audio_free/stage2_model_fine-tuning"
  ckpt: "results/MultiTask/audio_free/stage1_model_no_l2_before_injected"
  use_special_token: True

datasets:
  test_ann_path: "../data/clotho_aqa_v2/clotho_aqa_test_clean.json"
  save_file: "clotho_aqa_v2_pred_left"
  special_token: "[audio qa]"

run:
  batch_size_eval: 16
  evaluate: True
  # seed: 123
