model:
  ckpt: "results/MultiTask/audio_free_7B/stage1_model"

datasets:
  test_ann_path: "../data/UrbanSound8K/urbansound8K.json"
  save_file: "urban_pred"
  special_token: "[single event]"

run:
  batch_size_eval: 16
  evaluate: True 