model:
  ckpt: "results/MultiTask/audio_free_7B/stage1_model"

datasets:
  test_ann_path: "../data/AudioCaps/AudioCaps_audio_stage1_test.json"
  save_file: "audiocaps_pred"
  special_token: "[audio caption audiocaps]"

run:
  batch_size_eval: 16
  evaluate: True 