model:
  ckpt: "results/MultiTask/audio_free_7B/stage1_model"

datasets:
  test_ann_path: "../data/clotho_aqa/clotho_aqa_test_clean.json"
  save_file: "clotho_aqa_pred"
  special_token: "[audio qa]"

run:
  batch_size_eval: 16
  evaluate: True 
