model:
  ckpt: "results/MultiTask/audio_free_7B/stage1_model"

datasets:
  test_ann_path: "../data/FSD50k/fsd50k_eval.json"
  save_file: "FSD50k_pred"
  special_token: "[multi events]"

run:
  batch_size_eval: 16
  evaluate: True 