model:
  ckpt: "results/MultiTask/audio_free_7B/stage1_model"

datasets:
  test_ann_path: "../data/RAVDESS/RAVDESS_only_audio_test.json"
  # test_ann_path: "../data/RAVDESS/RAVDESS_only_audio_test_test.json"
  save_file: "RAVDESS_pred"
  special_token: "[emotion event]"

run:
  batch_size_eval: 8
  evaluate: True 