model:
  ckpt: "results/MultiTask/audio_free_7B/stage2_model"
  use_special_token: True

datasets:
  test_ann_path: "../data/openAQAData/combine_aqa_test.json"
  save_file: "open_pred"
  special_token: "[open ended]"

run:
  batch_size_eval: 1
  evaluate: True 
