model:
  ckpt: "results/MultiTask/audio_free_7B/stage1_model"

datasets:
  test_ann_path: "../data/beijing_opera/beijing_opera_test.json"
  # test_ann_path: "../data/beijing_opera/beijing_opera_test_test.json"
  save_file: "bjo_pred"
  special_token: "[instruction event]"

run:
  batch_size_eval: 16
  evaluate: True 