model:
  # ckpt: "results/MultiTask/audio_free/stage2_model"
  ckpt: "results/MultiTask/audio_free/stage2_model_only_openAQA"
  use_special_token: True


datasets:
  test_ann_path: "../data/MMAU/mmau-test-mini_AudioFree.json"
  save_file: "MMAU_mini_pred"
  special_token: "[open ended]"
  
  isAIRBench: False

run:
  batch_size_eval: 16
  log_freq: 50
  evaluate: True