model:
  ckpt: "results/MultiTask/audio_free_7B/stage1_model"

datasets:
  test_ann_path: "../data/VocalSound/vocalsound_test.json"
  save_file: "vocal_pred"
  special_token: "[vocal event]"

run:
  batch_size_eval: 16
  evaluate: True 