model:
  ckpt: "results/MultiTask/audio_free_7B/stage1_model"

datasets:
  test_ann_path: "../data/clothov2/ClothoV2_test.json"
  save_file: "clothov2_pred"
  special_token: "[audio caption clotho]"

run:
  batch_size_eval: 16
  evaluate: True 