model:
  ckpt: "results/MultiTask/audio_free_7B/stage1_model"

datasets:
  test_ann_path: "../data/MusicCaps/MusicCaps_test.json"
  save_file: "Music_pred"
  special_token: "[music caption]"

run:
  batch_size_eval: 16
  evaluate: True 
