model:
  name: "audiofree"
  # paths
  llama_path: "xxx"
  clap_path: "xxx"

  ckpt: "xxx"

  freeze_clap: True

  # Memory Bank setting
  use_memory_bank: False
  is_kmeans: True
  save_memory_dir: "xxx"
  k_nums: 32
  lambda: 0.3
  group_nums: 100
  iter_kmeans: 10
  temperature: 10
  number: 5172 #

  # mapper
  clap_dim: 1024
  mapper_dim: 1024
  prefix_length: 40
  clip_length: 40
  num_layers: 8
  mapping_type: "transformer"

  # noise
  noise_variance: 0.015
  uniform_noise: False

  # LoRA
  lora: True
  lora_rank: 8
  lora_alpha: 32
  lora_dropout: 0.1

  max_txt_len: 150
  end_sym: "</s>"

datasets:
  test_file: "xxx"
  task: "caption"
  question: None
  audiofree: True
  resampling_rate: 44100
  audio_duration: 7
  resample: True

generate:
  max_new_tokens: 200
  num_beams: 4
  do_sample: False
  min_length: 1
  temperature: 1.0
  no_repeat_ngram_size: 2
  repetition_penalty: 2.0
  length_penalty: 1.0
